version: "3.7"

services:
  app:
    container_name: app
    build:
      context: .
      target: base
    tty: true
    volumes:
       - ./:/code:cached
       - /code/node_modules
    ports:
      - 4200:4200

